### ISSUE TITLE
Failing to create_site

### ISSUE THREAD

**Issue by harini2040** [amngibson/nexpose-runner#20]
this is the stackTrace , while running nexpose-runner 
```
Successfully logged into the Nexpose Server!
Creating a nexpose site named updating-nexpose-runner-site
/usr/local/lib/ruby/gems/2.1.0/gems/nexpose-7.1.1/lib/nexpose/site.rb:180:in `included_addresses': wrong number of arguments (1 for 0) (ArgumentError)
	from /usr/local/lib/ruby/gems/2.1.0/gems/NexposeRunner-0.0.18b/lib/nexpose-runner/scan.rb:114:in `block in create_site'
	from /usr/local/lib/ruby/gems/2.1.0/gems/NexposeRunner-0.0.18b/lib/nexpose-runner/scan.rb:113:in `each'
	from /usr/local/lib/ruby/gems/2.1.0/gems/NexposeRunner-0.0.18b/lib/nexpose-runner/scan.rb:113:in `create_site'
	from /usr/local/lib/ruby/gems/2.1.0/gems/NexposeRunner-0.0.18b/lib/nexpose-runner/scan.rb:48:in `start'
	from /usr/local/lib/ruby/gems/2.1.0/gems/NexposeRunner-0.0.18b/bin/scan:20:in `<top (required)>'
	from /usr/local/bin/scan:23:in `load'
	from /usr/local/bin/scan:23:in `<main>'
```

It appear that its not able to iterate through the list (constructed well) of ip-address provided while running it .

**Comment by amngibson** [comment]
@harini2040 Thanks for the comment. It looks like you are using the BETA version of the gem "NexposeRunner-0.0.18b" we are working out a few kinks with change the underlying community gem for NEXPOSE made to method names. 

If you go back to using the stable non-BETA version: 0.0.15, it should work fine for you. We will release a new stable version with the upgraded Nexpose client as soon as we work out all the kinks.

**Comment by harini2040** [comment]
@amngibson , Thanks for the prompt reply. Any timeframe for that?

**Comment by sherzberg** [comment]
Hi @amngibson, @harini2040 is working with us to help you debug the beta and get nexpose client updated. Hope her debug output can help out.

**Comment by espoelstra** [comment]
Here's a patch to the code and tests to use the newer `include_asset` instead of the previous `included_addresses` call that was changed.

```From 9ee271f46a9362893992c517ce0c01b14ac77c92 Mon Sep 17 00:00:00 2001
From: Ethan Spoelstra <espoelstra@pithoslabs.com>
Date: Mon, 30 Oct 2017 21:00:27 +0000
Subject: [PATCH] Use new include_asset instead of included_addresses

---
 lib/nexpose-runner/scan.rb | 2 +-
 spec/scan_spec.rb          | 4 ++--
 2 files changed, 3 insertions(+), 3 deletions(-)

diff --git a/lib/nexpose-runner/scan.rb b/lib/nexpose-runner/scan.rb
index 74e1331..f3bfdeb 100755
--- a/lib/nexpose-runner/scan.rb
+++ b/lib/nexpose-runner/scan.rb
@@ -111,7 +111,7 @@ module NexposeRunner
       puts "Creating a nexpose site named #{run_details.site_name}"
       site = Nexpose::Site.new run_details.site_name, run_details.scan_template_id
       run_details.ip_addresses.each { |address|
-          site.included_addresses address
+          site.include_asset address
       }
       if run_details.engine_id
         site.engine_id = run_details.engine_id
diff --git a/spec/scan_spec.rb b/spec/scan_spec.rb
index 5345f38..f8670e0 100644
--- a/spec/scan_spec.rb
+++ b/spec/scan_spec.rb
@@ -158,7 +158,7 @@ describe 'nexpose-runner' do
 
       it 'should add the supplied ip address to the newly created site' do
         @expected_ips.split(',').each { |ip|
-          expect(@mock_nexpose_site).to receive(:included_addresses).with(ip)
+          expect(@mock_nexpose_site).to receive(:include_asset).with(ip)
         }
         NexposeRunner::Scan.start(@options)
       end
@@ -364,7 +364,7 @@ def get_mock_nexpose_site
                           .and_return(@mock_site_id)
 
   @expected_ips.split(',').each { |ip|
-    allow(mock_nexpose_site).to receive(:included_addresses).with(ip)
+    allow(mock_nexpose_site).to receive(:include_asset).with(ip)
   }
 
   allow(mock_nexpose_site).to receive(:save)
-- 
2.14.1
```

**Comment by espoelstra** [comment]
Thought it wasn't working, turns out it was an error in our script to call the gem. Working great with the changes I made above.

**Comment by amngibson** [comment]
@espoelstra Thanks for the help. I have pushed NexposeRunner-0.0.19b.gem with the changes you recommend. 
Once you validate everything is working great with the bet gem, we will merge and create a new 1.0.0 non-beta with these changes.

**Comment by xsnrg** [comment]
awesome, thanks!

**Comment by espoelstra** [comment]
Looks to be running well and no more timeouts since I think the default in Nexpose 7.1.1 went to 120 seconds. I'd give it my stamp of approval (it's a very small stamp). :1st_place_medal:
